@ECHO OFF
SETLOCAL ENABLEDELAYEDEXPANSION
SET FILES=
FOR /R %%f in (*cpp) DO (
    SET files=!files! %%f
)

SET ASSEMBLY=c-proj
SET COMPILER=-g -shared -Wvarargs -Wall -Werror
SET INCLUDE=-Iinclude
SET LINKER=-luser32
SET DEFINES=-DC-PROJ_DEBUG -DC-PROJ_EXPORT -D_CRT_SECURE_NO_WARNINGS

gcc %FILES% %COMPILER% -o ../bin/%ASSEMBLY%.dll %DEFINES% %INCLUDE% %LINKER%